# Generated by Django 5.1.4 on 2025-02-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.member'),
        ),
    ]
