# Generated by Django 5.1.4 on 2025-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categoryDescription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
