# Generated by Django 5.1.4 on 2025-01-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.TextField()),
                ('gender', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
